# Generated by Django 6.0.3 on 2026-03-11 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('capacity_kg', models.IntegerField(verbose_name='Capacidade em kg')),
                ('num_floors', models.IntegerField(verbose_name='Número de Andares')),
                ('installation_location', models.TextField(verbose_name='Local de Instalação')),
                ('installation_date', models.DateField(verbose_name='Data de Instalação')),
                ('status', models.CharField(choices=[('operacional', 'Operacional'), ('em_manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='operacional', max_length=20)),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
            ],
            options={
                'verbose_name': 'Elevador',
                'verbose_name_plural': 'Elevadores',
                'ordering': ['created_at'],
            },
        ),
    ]
