# Generated by Django 6.0.3 on 2026-03-11 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('tel', models.CharField(max_length=20, verbose_name='Telefone')),
            ],
        ),
        migrations.AlterField(
            model_name='elevator',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elevator.manufacturer', verbose_name='Fabricante'),
        ),
    ]
