# Generated by Django 6.0.3 on 2026-03-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0002_manufacturer_alter_elevator_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='Fabricante'),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
