# Generated by Django 6.0.3 on 2026-03-11 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0003_alter_elevator_manufacturer_delete_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('tel', models.CharField(max_length=20, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='elevator',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elevator.manufacturer', verbose_name='Fabricante'),
        ),
    ]
