# Generated by Django 6.0.3 on 2026-03-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0004_manufacturer_alter_elevator_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elevator',
            options={'ordering': ['-created_at'], 'verbose_name': 'Elevador', 'verbose_name_plural': 'Elevadores'},
        ),
    ]
