# Generated by Django 6.0.3 on 2026-03-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-created_at'], 'verbose_name': 'Manutenção', 'verbose_name_plural': 'Manutenções'},
        ),
        migrations.AlterModelOptions(
            name='providercompany',
            options={'verbose_name': 'Empresa Prestadora', 'verbose_name_plural': 'Empresas Prestadoras'},
        ),
    ]
